name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnowdb"
database_id = "dc341714-0ac2-4dec-9130-84c1310c3156"
